services:
  postgresql-zskarte:
    image: bitnamilegacy/postgresql:16.3.0
    container_name: postgresql-zskarte
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/bitnami/postgresql
      - ./packages/server/init:/docker-entrypoint-initdb.d
    ports:
      - 55432:5432
    environment:
      - POSTGRESQL_PASSWORD=supersecret123
      - POSTGRESQL_DATABASE=zskarte
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      start_period: 60s
      retries: 6
    networks:
      - zskarte

  pgadmin-zskarte:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-zskarte
    restart: unless-stopped
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      - ./packages/server/init/servers.json:/pgadmin4/servers.json
    ports:
      - 7050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@zskarte.ch
      - PGADMIN_DEFAULT_PASSWORD=zskarte
    networks:
      - zskarte

  server-zskarte:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-zskarte
    networks:
      - zskarte
    ports: [ 1337:1337 ]
    environment:
      - DATABASE_HOST=postgresql-zskarte
      - DATABASE_PORT=5432
    depends_on:
      postgresql-zskarte:
        condition: service_healthy
  app-zskarte:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app-zskarte
    ports: [ 4300:80 ]
    

networks:
  zskarte:
    driver: bridge
