/*
 * Copyright © 2018-2020 ZSO Bern Plus / PCi Fribourg
 *
 * This file is part of Zivilschutzkarte 2.
 *
 * Zivilschutzkarte 2 is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Zivilschutzkarte 2 is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * Zivilschutzkarte 2.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 */

import { Sign } from '../entity/sign';

export class Signs {
  public static SIGNS: Sign[] = [
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/ABC Dekontaminationsstelle.svg',
      de: 'ABC Dekontaminationsstelle',
      en: 'ABC Dekontaminationsstelle',
      fr: 'Place de décontamination',
    },
    {
      type: 'Polygon',
      color: '#0000FF',
      src: 'BABS/Absperrung Einsatzraum.svg',
      de: 'Absperrung Einsatzraum',
      en: 'Absperrung Einsatzraum',
      fr: 'Barrage du secteur d’engagement',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Absperrung Verkehrswege.svg',
      de: 'Absperrung Verkehrswege',
      en: 'Absperrung Verkehrswege',
      fr: 'Fermeture de la route',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Achse fuer Ei, Rttg, Vsg.svg',
      de: 'Achse für Ei, Rttg, Vsg',
      en: 'Achse für Ei, Rttg, Vsg',
      fr: 'Axe d’engagement pour le sauvetage, l’approvisionnement, etc.',
      style: 'dash',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Angehoerigensammelstelle.svg',
      de: 'Angehörigensammelstelle',
      en: 'Angehörigensammelstelle',
      fr: 'Poste collecteur pour les proches',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Atomunfall.svg',
      de: 'Atomunfall',
      en: 'Atomunfall',
      fr: 'Accident nucléaire',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Autounfall.svg',
      de: 'Autounfall',
      en: 'Autounfall',
      fr: 'Accident de circulation automobile',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Beabsichtigte Erkundung.svg',
      de: 'Beabsichtigte Erkundung',
      en: 'Beabsichtigte Erkundung',
      fr: 'Exploration / Reconnaissances prévues',
      arrow: 'filled',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Beabsichtigter Einsatz.svg',
      de: 'Beabsichtigter Einsatz',
      en: 'Beabsichtigter Einsatz',
      fr: 'Engagements prévus',
      style: 'dash',
      arrow: 'filled',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Beabsichtigte Verschiebung.svg',
      de: 'Beabsichtigte Verschiebung',
      en: 'Beabsichtigte Verschiebung',
      fr: 'Mouvements prévus',
      style: 'dash',
      hideIcon: true,
      arrow: 'filled',
      strokeWidth: 1.5,
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Beobachtung.svg',
      de: 'Beobachtung',
      en: 'Beobachtung',
      fr: 'Observation',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Beschaedigung.svg',
      de: 'Beschädigung',
      en: 'Beschädigung',
      fr: 'Dégât',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Betreuungsstelle.svg',
      de: 'Betreuungsstelle',
      en: 'Betreuungsstelle',
      fr: 'Poste d’assistance',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Betriebsstoffabgabestelle.svg',
      de: 'Betriebsstoffabgabestelle',
      en: 'Betriebsstoffabgabestelle',
      fr: 'Station de carburant',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Bezirksfuehrungsorgan.svg',
      de: 'Bezirksführungsorgan',
      en: 'Bezirksführungsorgan',
      fr: 'Organe de conduite de district',
    },
    {
      type: 'Polygon',
      color: '#948B68',
      src: 'BABS/Biologisch verseuchtes Gebiet.svg',
      de: 'Biologisch verseuchtes Gebiet',
      en: 'Biologisch verseuchtes Gebiet',
      fr: 'Zone biologiquement contaminée',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Biounfall.svg',
      de: 'Biounfall',
      en: 'Biounfall',
      fr: 'Accident biologique',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/B Laboratorium.svg',
      de: 'B Laboratorium',
      en: 'B Laboratorium',
      fr: 'Laboratoire B',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Bombenanschlag.svg',
      de: 'Bombenanschlag',
      en: 'Bombenanschlag',
      fr: 'Attentat à la bombe',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Bombendrohung.svg',
      de: 'Bombendrohung',
      en: 'Bombendrohung',
      fr: 'Menace à la bombe',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brandanschlag.svg',
      de: 'Brandanschlag',
      en: 'Brandanschlag',
      fr: 'Incendie criminel',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brand einzelnes Gebaeude Flamme.svg',
      de: 'Brand einzelnes Gebäude Flamme',
      en: 'Brand einzelnes Gebäude Flamme',
      fr: 'Incendie isolé',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brand.svg',
      de: 'Brand',
      en: 'Brand',
      fr: 'Incendie',
    },
    {
      type: 'LineString',
      color: '#FF0000',
      src: 'BABS/Branduebergriff erfolgt - Signatur.svg',
      de: 'Brandübergriff erfolgt',
      en: 'Brandübergriff erfolgt',
      fr: 'Extension du feu',
      example: 'Branduebergriff erfolgt - Beispiel.svg',
    },
    {
      type: 'LineString',
      color: '#FF0000',
      src: 'BABS/Branduebergriffsgefahr - Signatur.svg',
      de: 'Brandübergriffsgefahr',
      en: 'Brandübergriffsgefahr',
      fr: "Danger d'extension",
      example: 'Branduebergriffsgefahr - Beispiel.svg',
      style: 'dash',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Brandzone Flaechenbrand.svg',
      de: 'Brandzone Flächenbrand',
      en: 'Brandzone Flächenbrand',
      fr: 'Zone en feu',
      hideIcon: true,
      fillStyle: {
        name: 'hatch',
        size: 1,
        spacing: 8,
      },
      fillOpacity: 1,
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Chemieunfall.svg',
      de: 'Chemieunfall',
      en: 'Chemieunfall',
      fr: 'Accident chimique',
    },
    {
      type: 'Polygon',
      color: '#948B68',
      src: 'BABS/Chemievergiftetes Gebiet gasfoermig - fluechtig.svg',
      de: 'Chemievergiftetes Gebiet gasförmig - flüchtig',
      en: 'Chemievergiftetes Gebiet gasförmig - flüchtig',
      fr: 'Zone chimiquement contaminée gazeux - volatil',
    },
    {
      type: 'Polygon',
      color: '#948B68',
      src: 'BABS/Chemievergiftete Zone fluessig - sesshaft.svg',
      de: 'Chemievergiftete Zone flüssig - sesshaft',
      en: 'Chemievergiftete Zone flüssig - sesshaft',
      fr: 'Zone chimiquement contaminée liquide',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Chemikalien.svg',
      de: 'Chemikalien',
      en: 'Chemikalien',
      fr: 'Chimique',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Debriefingstelle.svg',
      de: 'Debriefingstelle',
      en: 'Debriefingstelle',
      fr: 'Poste de débriefing',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Demo gewaltlos.svg',
      de: 'Demo gewaltlos',
      en: 'Demo gewaltlos',
      fr: 'Manifestation',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Demo gewaltsam.svg',
      de: 'Demo gewaltsam',
      en: 'Demo gewaltsam',
      fr: 'Manifestation avec exactions',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Drohung.svg',
      de: 'Drohung',
      en: 'Drohung',
      fr: 'Menace',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Duerre.svg',
      de: 'Dürre',
      en: 'Dürre',
      fr: 'Sécheresse',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Durchgefuehrte Erkundung.svg',
      de: 'Durchgeführte Erkundung',
      en: 'Durchgeführte Erkundung',
      fr: 'Exploration / Reconnaissances exécutées',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Durchgefuehrter Einsatz.svg',
      de: 'Durchgeführter Einsatz',
      en: 'Durchgeführter Einsatz',
      fr: 'Engagements exécutés',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Durchgefuehrte Verschiebung.svg',
      de: 'Durchgeführte Verschiebung',
      en: 'Durchgeführte Verschiebung',
      fr: 'Mouvements exécutés',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Eingesperrte - Abgeschnittene.svg',
      de: 'Eingesperrte - Abgeschnittene',
      en: 'Eingesperrte - Abgeschnittene',
      fr: 'Personnes enfermées ou retranchées',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Einsatzleiter.svg',
      de: 'Einsatzleiter',
      en: 'Einsatzleiter',
      fr: 'Chef d’intervention',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Einsatzleitung.svg',
      de: 'Einsatzleitung',
      en: 'Einsatzleitung',
      fr: 'Direction d’intervention',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Einsatzzentrale.svg',
      de: 'Einsatzzentrale',
      en: 'Einsatzzentrale',
      fr: 'Centrale d‘engagement',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Eisenbahnunglueck.svg',
      de: 'Eisenbahnunglück',
      en: 'Eisenbahnunglück',
      fr: 'Accident ferroviaire',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Elektrizitaet.svg',
      de: 'Elektrizität',
      en: 'Elektrizität',
      fr: 'Electricité',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Energieausfall.svg',
      de: 'Energieausfall',
      en: 'Energieausfall',
      fr: 'Panne énergétique',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Epidemie.svg',
      de: 'Epidemie',
      en: 'Epidemie',
      fr: 'Epidemie',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Erdbeben.svg',
      de: 'Erdbeben',
      en: 'Erdbeben',
      fr: 'Tremblement de terre',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Erdrutsch.svg',
      de: 'Erdrutsch',
      en: 'Erdrutsch',
      fr: 'Glissement de terrain',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Explosion.svg',
      de: 'Explosion',
      en: 'Explosion',
      fr: 'Explosion',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Explosionsherd - Signatur.svg',
      de: 'Explosionsherd',
      en: 'Explosionsherd',
      fr: 'Foyer d’explosion',
      example: 'Explosionsherd - Beispiel.svg',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Fahrzeugplatz.svg',
      de: 'Fahrzeugplatz',
      en: 'Fahrzeugplatz',
      fr: 'Place pour véhicules',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Fluechtlinge.svg',
      de: 'Flüchtlinge',
      en: 'Flüchtlinge',
      fr: 'Réfugiés',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Flugzeugabsturz.svg',
      de: 'Flugzeugabsturz',
      en: 'Flugzeugabsturz',
      fr: 'Catastrophe aérienne',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Gas.svg',
      de: 'Gas',
      en: 'Gas',
      fr: 'Gaz',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Gebaeudeeinsturz.svg',
      de: 'Gebäudeeinsturz',
      en: 'Gebäudeeinsturz',
      fr: 'Immeuble effondré',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Gefahr durch Loeschen mit Wasser.svg',
      de: 'Gefahr durch Löschen mit Wasser',
      en: 'Gefahr durch Löschen mit Wasser',
      fr: "Danger en cas d'extinction avec de l'eau",
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Gefahrentafel mit UN-Nummer.svg',
      de: 'Gefahrentafel mit UN-Nummer',
      en: 'Gefahrentafel mit UN-Nummer',
      fr: 'Plaque de danger avec numéro ONU',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Gefahr fuer Grundwasser.svg',
      de: 'Gefahr für Grundwasser',
      en: 'Gefahr für Grundwasser',
      fr: 'Danger pour les eaux de surface et/ou nappes souterraines',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Gemeindefuehrungsorgan.svg',
      de: 'Gemeindeführungsorgan',
      en: 'Gemeindeführungsorgan',
      fr: 'Organe de conduite communal',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Gruppenfuehrer.svg',
      de: 'Gruppenführer',
      en: 'Gruppenführer',
      fr: 'Chef de groupe',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Gruppe.svg',
      de: 'Gruppe',
      en: 'Gruppe',
      fr: 'Groupe',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Helikopterlandeplatz.svg',
      de: 'Helikopterlandeplatz',
      en: 'Helikopterlandeplatz',
      fr: 'Place d’atterrissage pour hélicoptère',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Informationsstelle.svg',
      de: 'Informationsstelle',
      en: 'Informationsstelle',
      fr: 'Point d’information',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Informationszentrum.svg',
      de: 'Informationszentrum',
      en: 'Informationszentrum',
      fr: 'Centre de presse',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Infrastrukturschaden.svg',
      de: 'Infrastrukturschaden',
      en: 'Infrastrukturschaden',
      fr: 'Dommages aux infrastructures',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kadaversammelstelle.svg',
      de: 'Kadaversammelstelle',
      en: 'Kadaversammelstelle',
      fr: 'Poste collecteur de cadavres d’animaux',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Kanalisationsausfall.svg',
      de: 'Kanalisationsausfall',
      en: 'Kanalisationsausfall',
      fr: 'Egoûts défectueux',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kantonales Fuehrungsorgan.svg',
      de: 'Kantonales Führungsorgan',
      en: 'Kantonales Führungsorgan',
      fr: 'Organe de conduite cantonal',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/KGS Sammelpunkt.svg',
      de: 'KGS Sammelpunkt',
      en: 'KGS Sammelpunkt',
      fr: 'Point de collecte PBC',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/KGS Notdepot.svg',
      de: 'KGS Notdepot',
      en: 'KGS Notdepot',
      fr: 'Dépôt d’urgence PBC',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/KGS Notlager.svg',
      de: 'KGS Notlager',
      en: 'KGS Notlager',
      fr: 'Entrepôt d’urgence PBC',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kommandoposten Front.svg',
      de: 'Kommandoposten Front',
      en: 'Kommandoposten Front',
      fr: 'PC engagement',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kommandoposten Rueckwaertiges.svg',
      de: 'Kommandoposten Rückwärtiges',
      en: 'Kommandoposten Rückwärtiges',
      fr: 'PC opérations',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Kommunikationsstoerung.svg',
      de: 'Kommunikationsstörung',
      en: 'Kommunikationsstörung',
      fr: 'Perturbation de la communication',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kompanie.svg',
      de: 'Kompanie',
      en: 'Kompanie',
      fr: 'Compagnie',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kontrollstelle.svg',
      de: 'Kontrollstelle',
      en: 'Kontrollstelle',
      fr: 'Point de contrôle',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Kontrollzentrum.svg',
      de: 'Kontrollzentrum',
      en: 'Kontrollzentrum',
      fr: 'Centre de contrôle',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Lawine.svg',
      de: 'Lawine',
      en: 'Lawine',
      fr: 'Avalanche',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Massenpanik.svg',
      de: 'Massenpanik',
      en: 'Massenpanik',
      fr: 'Effets de panique',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Materialdepot.svg',
      de: 'Materialdepot',
      en: 'Materialdepot',
      fr: 'Dépôt de matériel',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Mobile Einsatzzentrale.svg',
      de: 'Mobile Einsatzzentrale',
      en: 'Mobile Einsatzzentrale',
      fr: 'Centrale d’engagement mobile',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Obdachlose.svg',
      de: 'Obdachlose',
      en: 'Obdachlose',
      fr: 'Sans-abri',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Oelverschmutzung.svg',
      de: 'Ölverschmutzung',
      en: 'Ölverschmutzung',
      fr: 'Pollution aux hydrocarbures',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Offizier - Zugfuehrer.svg',
      de: 'Offizier - Zugführer',
      en: 'Offizier - Zugführer',
      fr: 'Officier',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Patientensammelstelle.svg',
      de: 'Patientensammelstelle',
      en: 'Patientensammelstelle',
      fr: 'Poste collecteur de patients',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Pforte.svg',
      de: 'Pforte',
      en: 'Pforte',
      fr: 'Porte',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Pluenderung.svg',
      de: 'Plünderung',
      en: 'Plünderung',
      fr: 'Pillage',
    },
    {
      type: 'Polygon',
      color: '#948B68',
      src: 'BABS/Radioaktives Gebiet.svg',
      de: 'Radioaktives Gebiet',
      en: 'Radioaktives Gebiet',
      fr: 'Zone radioactive',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Radioaktive Stoffe.svg',
      de: 'Radioaktive Stoffe',
      en: 'Radioaktive Stoffe',
      fr: 'Substances radioactives',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Regionales Fuehrungsorgan.svg',
      de: 'Regionales Führungsorgan',
      en: 'Regionales Führungsorgan',
      fr: 'Organe de conduite régional',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Rutschgebiet.svg',
      de: 'Rutschgebiet',
      en: 'Rutschgebiet',
      fr: 'Glissement de terrain',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Sabotage.svg',
      de: 'Sabotage',
      en: 'Sabotage',
      fr: 'Sabotage',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Sammelstelle.svg',
      de: 'Sammelstelle',
      en: 'Sammelstelle',
      fr: 'Poste collecteur',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Sanitaetshilfsstelle.svg',
      de: 'Sanitätshilfsstelle',
      en: 'Sanitätshilfsstelle',
      fr: 'Poste médical avancé',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Sanitaetsumladestelle.svg',
      de: 'Sanitätsumladestelle',
      en: 'Sanitätsumladestelle',
      fr: 'Poste sanitaire de transfert',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Sperre.svg',
      de: 'Sperre',
      en: 'Sperre',
      fr: 'Barrage',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Standort mobile Fuehrungsstelle.svg',
      de: 'Standort mobile Führungsstelle',
      en: 'Standort mobile Führungsstelle',
      fr: 'Poste de conduite',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Starkniederschlag.svg',
      de: 'Starkniederschlag',
      en: 'Starkniederschlag',
      fr: 'Fortes précipitations',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Stau.svg',
      de: 'Stau',
      en: 'Stau',
      fr: 'Embouteillage',
    },
    {
      type: 'LineString',
      color: '#FF0000',
      src: 'BABS/Str erschwert befahrbar - begehbar.svg',
      de: 'Strasse erschwert befahrbar - begehbar',
      en: 'Strasse erschwert befahrbar - begehbar',
      fr: 'Route difficilement praticable pour les vhc, possible pour les piétons',
      style: 'dash',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Streugutsammelstelle.svg',
      de: 'Streugutsammelstelle',
      en: 'Streugutsammelstelle',
      fr: 'Poste collecteur des objets trouvés',
    },
    {
      type: 'LineString',
      color: '#FF0000',
      src: 'BABS/Str nicht befahrbar - schwer begehbar.svg',
      de: 'Strasse nicht befahrbar - schwer begehbar',
      en: 'Strasse nicht befahrbar - schwer begehbar',
      fr: 'Route impraticable pour les vhc et difficile pour les piétons',
    },
    {
      type: 'LineString',
      color: '#FF0000',
      src: 'BABS/Str unpassierbar - gesperrt.svg',
      de: 'Strasse unpassierbar - gesperrt',
      en: 'Strasse unpassierbar - gesperrt',
      fr: 'Route impraticable / barrée',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Stuetzpunkt.svg',
      de: 'Stützpunkt',
      en: 'Stützpunkt',
      fr: 'Point de sécurité',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Sturm.svg',
      de: 'Sturm',
      en: 'Sturm',
      fr: 'Tempête',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Tankloeschfahrzeug.svg',
      de: 'Tanklöschfahrzeug',
      en: 'Tanklöschfahrzeug',
      fr: 'Tonne-pompe',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Teilzerstoerung.svg',
      de: 'Teilzerstörung',
      en: 'Teilzerstörung',
      fr: 'Destruction partielle',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Terroranschlag.svg',
      de: 'Terroranschlag',
      en: 'Terroranschlag',
      fr: 'Acte de terrorisme',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Tierseuche.svg',
      de: 'Tierseuche',
      en: 'Tierseuche',
      fr: 'Epizootie',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Totalzerstoerung.svg',
      de: 'Totalzerstörung',
      en: 'Totalzerstörung',
      fr: 'Destruction totale',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Totensammelstelle.svg',
      de: 'Totensammelstelle',
      en: 'Totensammelstelle',
      fr: 'Poste collecteur de cadavres',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Tote.svg',
      de: 'Tote',
      en: 'Tote',
      fr: 'Morts',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Trinkwasserabgabestelle.svg',
      de: 'Trinkwasserabgabestelle',
      en: 'Trinkwasserabgabestelle',
      fr: 'Poste de distribution d’eau potable',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Trupp.svg',
      de: 'Trupp',
      en: 'Trupp',
      fr: 'Patrouille',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Ueberschwemmtes Gebiet.svg',
      de: 'Überschwemmtes Gebiet',
      en: 'Überschwemmtes Gebiet',
      fr: 'Zone inondée ou submergée',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Ueberschwemmung.svg',
      de: 'Überschwemmung',
      en: 'Überschwemmung',
      fr: 'Inondation',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Ueberwachung.svg',
      de: 'Überwachung',
      en: 'Überwachung',
      fr: 'Surveillance',
    },
    {
      type: 'LineString',
      color: '#0000FF',
      src: 'BABS/Umleitung.svg',
      de: 'Umleitung',
      en: 'Umleitung',
      fr: 'Déviations',
    },
    {
      type: 'Point',
      color: '#FF9100',
      src: 'BABS/Unfall.svg',
      de: 'Unfall',
      en: 'Unfall',
      fr: 'Accident',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Verkehrsposten.svg',
      de: 'Verkehrsposten',
      en: 'Verkehrsposten',
      fr: 'Poste de circulation',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Verletztennest.svg',
      de: 'Verletztennest',
      en: 'Verletztennest',
      fr: 'Nid de blessés',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Verletzte.svg',
      de: 'Verletzte',
      en: 'Verletzte',
      fr: 'Patients (blessés)',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Vermisste.svg',
      de: 'Vermisste',
      en: 'Vermisste',
      fr: 'Disparus',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Verpflegungsabgabestelle.svg',
      de: 'Verpflegungsabgabestelle',
      en: 'Verpflegungsabgabestelle',
      fr: 'Poste de distribution de subsistance',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Wasservsgausfall.svg',
      de: 'Wasserversorgungsausfall',
      en: 'Wasserversorgungsausfall',
      fr: 'Interruption de l’approvisionnement en eau',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Wasserwerfer.svg',
      de: 'Wasserwerfer',
      en: 'Wasserwerfer',
      fr: 'Canon à eau',
    },
    {
      type: 'Polygon',
      color: '#FF0000',
      src: 'BABS/Zerstoerte Zone einer Ortschaft.svg',
      de: 'Zerstörte Zone einer Ortschaft',
      en: 'Zerstörte Zone einer Ortschaft',
      fr: 'Zone sinistrée, impraticable à l’intérieur d’une localité',
      hideIcon: true,
      fillStyle: {
        name: 'cross',
        size: 1,
        spacing: 8,
      },
      fillOpacity: 1,
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BABS/Zug.svg',
      de: 'Zug',
      en: 'Zug',
      fr: 'Section',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Absperrung mit Ueberwachung.svg',
      de: 'Absperrung mit Ueberwachung',
      en: 'Absperrung mit Ueberwachung',
      fr: 'Barrière avec surveillance ',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brand einzelnes Gebaeude - Beispiel.svg',
      de: 'Brand einzelnes Gebaeude - Beispiel',
      en: 'Brand einzelnes Gebaeude - Beispiel',
      fr: 'Incendie bâtiment unique - exemple',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brand einzelnes Gebaeude - Signatur.svg',
      de: 'Brand einzelnes Gebaeude - Signatur',
      en: 'Brand einzelnes Gebaeude - Signatur',
      fr: 'Incendie bâtiment unique - signature',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brand mehrerer Gebaeude - Beispiel.svg',
      de: 'Brand mehrerer Gebaeude - Beispiel',
      en: 'Brand mehrerer Gebaeude - Beispiel',
      fr: 'Incendie dans plusieurs bâtiments - exemple',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Brand mehrerer Gebaeude - Signatur.svg',
      de: 'Brand mehrerer Gebaeude - Signatur',
      en: 'Brand mehrerer Gebaeude - Signatur',
      fr: 'Incendie dans plusieurs immeubles - signature',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Branduebergriff erfolgt - Beispiel.svg',
      de: 'Branduebergriff erfolgt - Beispiel',
      en: 'Branduebergriff erfolgt - Beispiel',
      fr: 'Une attaque de feu a lieu - exemple',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Branduebergriffsgefahr - Beispiel.svg',
      de: 'Branduebergriffsgefahr - Beispiel',
      en: 'Branduebergriffsgefahr - Beispiel',
      fr: 'Attaque de feu - exemple',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Explosionsherd - Beispiel.svg',
      de: 'Explosionsherd - Beispiel',
      en: 'Explosionsherd - Beispiel',
      fr: 'Poêle à explosion - exemple',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Feuerwehr.svg',
      de: 'Feuerwehr',
      en: 'Feuerwehr',
      fr: 'Pompiers',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BSM/Komm Ausfall Nat.svg',
      de: 'Komm Ausfall Nat - Mobilnetz',
      en: 'Komm Ausfall Nat - Mobilnetz',
      fr: 'Échec de la comm. Nat - Réseau cellulaire',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BSM/Komm Ausfall Tel.svg',
      de: 'Komm Ausfall Tel - Festnetz',
      en: 'Komm Ausfall Tel - Festnetz',
      fr: 'Échec de la comm. Tel - ligne fixe',
    },
    {
      type: 'Point',
      color: '#000000',
      src: 'BSM/Markierung Feuer.svg',
      de: 'Markierung Feuer',
      en: 'Markierung Feuer',
      fr: 'Marquer le feu',
    },
    {
      type: 'Point',
      color: '#000000',
      src: 'BSM/Markierung Gefaehrliche Stoffe.svg',
      de: 'Markierung Gefaehrliche Stoffe',
      en: 'Markierung Gefaehrliche Stoffe',
      fr: 'Marquage des substances dangereuses',
    },
    {
      type: 'Point',
      color: '#000000',
      src: 'BSM/Markierung Rettungen.svg',
      de: 'Markierung Rettungen',
      en: 'Markierung Rettungen',
      fr: 'Marquage des sauvetages',
    },
    {
      type: 'Point',
      color: '#000000',
      src: 'BSM/Markierung Unfall.svg',
      de: 'Markierung Unfall',
      en: 'Markierung Unfall',
      fr: 'Marque d\'accident ',
    },
    {
      type: 'Point',
      color: '#000000',
      src: 'BSM/Markierung Wasser.svg',
      de: 'Markierung Wasser',
      en: 'Markierung Wasser',
      fr: 'Marquage de l\'eau ',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Obdachlosensammelstelle.svg',
      de: 'Obdachlosensammelstelle',
      en: 'Obdachlosensammelstelle',
      fr: 'Point de rassemblement sans abri ',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Personenbergungsuebersicht - Beispiel.svg',
      de: 'Personenbergungsuebersicht - Beispiel',
      en: 'Personenbergungsuebersicht - Beispiel',
      fr: 'Vue d\'ensemble de sauvetage - exemple',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Personenbergungsuebersicht - Leerraster.svg',
      de: 'Personenbergungsuebersicht - Leerraster',
      en: 'Personenbergungsuebersicht - Leerraster',
      fr: 'Vue d\'ensemble de sauvetage - grille vide',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Polizei.svg',
      de: 'Polizei',
      en: 'Polizei',
      fr: 'Police',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Schadengebiet - Schadenraum.svg',
      de: 'Schadengebiet - Schadenraum',
      en: 'Schadengebiet - Schadenraum',
      fr: 'Zone de dégâts',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BSM/Schadengebiet, Schadenraum.svg',
      de: 'Schadengebiet, Schadenraum',
      en: 'Schadengebiet, Schadenraum',
      fr: 'Zone de dégâts',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Spital.svg',
      de: 'Spital',
      en: 'Hôpital',
      fr: 'Spital',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BSM/Stromausfall.svg',
      de: 'Stromausfall',
      en: 'Stromausfall',
      fr: 'Panne électrique',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Truemmerbereich - Beispiel.svg',
      de: 'Truemmerbereich - Beispiel',
      en: 'Truemmerbereich - Beispiel',
      fr: 'Zone de débris - exemple',
    },
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Truemmerbereich - Signatur.svg',
      de: 'Truemmerbereich - Signatur',
      en: 'Truemmerbereich - Signatur',
      fr: 'Zone de débris - signature',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Verwaltungskreisfuehrungsorgan.svg',
      de: 'Verwaltungskreisfuehrungsorgan',
      en: 'Verwaltungskreisfuehrungsorgan',
      fr: 'Organe de gestion du district administratif',
    },
    {
      type: 'Point',
      color: '#0000FF',
      src: 'BSM/Zivilschutz.svg',
      de: 'Zivilschutz',
      en: 'Zivilschutz',
      fr: 'Défense civile',
    },    
    {
      type: 'Point',
      color: '#FF0000',
      src: 'BABS/Ziviles Fuehrungsorgan.svg',
      de: 'Ziviles Fuehrungsorgan',
      en: 'Ziviles Fuehrungsorgan',
      fr: 'Organe exécutif civil',
    },
  ];

  public static getSignBySource(src: string) {
    for (const sig of Signs.SIGNS) {
      if (sig.src === src) {
        return sig;
      }
    }
    return null;
  }
}
