apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_NAME}-backup
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  schedule: '30 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: dbbackup
              image: switzerchees/dbbackup:1.1.2
              env:
                - name: BACKUP_DRIVER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: BACKUP_DRIVER
                - name: BACKUP_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: BACKUP_DATABASE
                - name: BACKUP_DIR
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: BACKUP_DIR
                - name: BACKUP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: BACKUP_PASSWORD
                - name: BACKUP_RETENTION
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: BACKUP_RETENTION
                - name: CONNECTION_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: CONNECTION_HOST
                - name: CONNECTION_PORT
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: CONNECTION_PORT
                - name: CONNECTION_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: CONNECTION_USER
                - name: CONNECTION_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: CONNECTION_PASSWORD
                - name: WEBDAV_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: WEBDAV_URL
                - name: WEBDAV_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: WEBDAV_USER
                - name: WEBDAV_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: WEBDAV_PASSWORD
                - name: WEBDAV_PATH
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: WEBDAV_PATH
                - name: PINGCHECK_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-backup
                      key: PINGCHECK_URL
              resources:
                requests:
                  cpu: 1m
                  memory: 128Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi