apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-backup
  namespace: ${KUBERNETES_NAMESPACE}
type: Opaque
stringData:
  BACKUP_DATABASE: ${DB_NAME}
  BACKUP_DRIVER: postgres
  BACKUP_DIR: ./backups
  BACKUP_PASSWORD: ${BACKUP_ENCRYPTION_PASSWORD}
  BACKUP_RETENTION: '672'
  CONNECTION_HOST: ${DB_HOST}
  CONNECTION_PORT: '${DB_PORT}'
  CONNECTION_USER: ${DB_USER}
  CONNECTION_PASSWORD: ${DB_PASSWORD}
  WEBDAV_URL: ${BACKUP_WEBDAV_URL}
  WEBDAV_USER: ${BACKUP_WEBDAV_USER}
  WEBDAV_PASSWORD: ${BACKUP_WEBDAV_PASSWORD}
  WEBDAV_PATH: ${DB_NAME}
  PINGCHECK_URL: ${BACKUP_PINGCHECK_URL}