apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${KUBERNETES_NAMESPACE}
  labels:
    app: ${APP_NAME}
    service: api
    stage: ${STAGE}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
      service: api
      stage: ${STAGE}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        service: api
        stage: ${STAGE}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${FULL_IMAGE_NAME}
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 45
            failureThreshold: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            periodSeconds: 5
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: db_host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: db_port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: db_name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: db_password
            - name: DATABASE_SSL
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: db_ssl
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: admin_jwt_secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: jwt_secret
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: app_keys
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: api_token_salt
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: transfer_token_salt
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: base_url
            - name: STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: storage_account
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: storage_account_key
            - name: STORAGE_URL
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: storage_url
            - name: STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: strapi-envs
                  key: storage_container_name
            - name: STORAGE_PROVIDER
              value: azure
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: 1337
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
