apiVersion: v1
kind: Secret
metadata:
  namespace: ${KUBERNETES_NAMESPACE}
  name: server-envs
type: Opaque
stringData:
  db_host: ${DB_HOST}
  db_port: "${DB_PORT}"
  db_name: ${DB_NAME}
  db_user: ${DB_USER}
  db_password: ${DB_PASSWORD}
  db_ssl: "${DB_SSL}"
  run_migrations_on_boot: "${RUN_MIGRATIONS_ON_BOOT}"
  better_auth_secret: ${BETTER_AUTH_SECRET}
  better_auth_url: ${BETTER_AUTH_URL}
  trusted_origins: ${TRUSTED_ORIGINS}
  proxy_allowed_hosts: ${PROXY_ALLOWED_HOSTS}
  sign_key_type: ${SIGN_KEY_TYPE}
  sign_private_key_passphrase: ${SIGN_PRIVATE_KEY_PASSPHRASE}
  skip_external_ip: "${SKIP_EXTERNAL_IP}"
  storage_provider: ${STORAGE_PROVIDER}
  storage_azure_account: ${STORAGE_AZURE_ACCOUNT}
  storage_azure_account_key: ${STORAGE_AZURE_ACCOUNT_KEY}
  storage_azure_container_name: ${STORAGE_CONTAINER_NAME}
  storage_azure_service_base_url: ${STORAGE_AZURE_SERVICE_BASE_URL}
  maplayer_generation_enabled: "${MAPLAYER_GENERATION_ENABLED}"
