apiVersion: v1
kind: Secret
metadata:
  namespace: ${KUBERNETES_NAMESPACE}
  name: strapi-envs
type: Opaque
stringData:
  db_host: ${DB_HOST}
  db_port: "${DB_PORT}"
  db_name: ${DB_NAME}
  db_user: ${DB_USER}
  db_password: ${DB_PASSWORD}
  db_ssl: "true"
  admin_jwt_secret: ${ADMIN_JWT_SECRET}
  jwt_secret: ${ADMIN_JWT_SECRET}
  app_keys: ${APP_KEYS}
  api_token_salt: ${API_TOKEN_SALT}
  transfer_token_salt: ${TRANSFER_TOKEN_SALT}
  storage_account: ${STORAGE_ACCOUNT}
  storage_account_key: ${STORAGE_ACCOUNT_KEY}
  storage_url: ${STORAGE_URL}
  storage_container_name: ${STORAGE_CONTAINER_NAME}
  base_url: https://${BASE_URL}
