name: Build
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.7]

    steps:
      - uses: actions/checkout@v1

      #- name: Cache node modules
       # uses: actions/cache@v1
        #with:
         # path: ~/.npm
          #key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          #restore-keys: |
           # ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build
        run: |
          npm install
          npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude '/.htaccess'
          path: dist/zskarte/
          remote_path: ${{ secrets.SERVER_PATH_DEV }}
          remote_host: ${{ secrets.SERVER_HOSTNAME }}
          remote_user: ${{ secrets.SERVER_LOGIN }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
