on:
  push:
    branches:
      - dev

env:
  STAGE: test
  DOCKERHUB_USERNAME: zskarte
  KUBERNETES_NAMESPACE: zskarte-test
  APP_NAME: zskarte-server
  FULL_IMAGE_NAME: zskarte/zskarte-server:${{ github.sha }}
  LETSENCRYPT_STAGE: prod
  DB_HOST: postgresql.postgresql.svc.cluster.local
  DB_PORT: 5432
  DB_NAME: zskarte-test
  DB_USER: zskarte
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  ADMIN_JWT_SECRET: ${{ secrets.STRAPI_ADMIN_JWT_SECRET_DEV }}
  JWT_SECRET: ${{ secrets.STRAPI_JWT_SECRET_DEV }}
  APP_KEYS: ${{ secrets.STRAPI_APP_KEYS_DEV }}
  API_TOKEN_SALT: ${{ secrets.STRAPI_API_TOKEN_SALT_DEV }}
  TRANSFER_TOKEN_SALT: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT_DEV }}
  BASE_URL: api-test.zskarte.ch
  STORAGE_ACCOUNT: zskarte
  STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
  STORAGE_URL: https://zskarte.blob.core.windows.net
  STORAGE_CONTAINER_NAME: zskarte-dev
  BACKUP_ENCRYPTION_PASSWORD: ${{ secrets.BACKUP_ENCRYPTION_PASSWORD }}
  BACKUP_WEBDAV_URL: https://nextcloud.hackerman.ch/remote.php/dav/files/d4y-backup
  BACKUP_WEBDAV_USER: d4y-backup
  BACKUP_WEBDAV_PASSWORD: ${{ secrets.BACKUP_WEBDAV_PASSWORD }}
  BACKUP_PINGCHECK_URL: https://uptime.digital4you.ch/api/push/zWihzwC36N?status=up&msg=OK&ping=

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .azure/k8s/namespace.yml
            .azure/k8s/strapi-envs.yml
            .azure/k8s/deployment.yml
            .azure/k8s/service.yml
            .azure/k8s/ingress.yml
            .azure/k8s/backup/secrets.yml
            .azure/k8s/backup/cronjob.yml
          replacement-method: defined
        env:
          IMAGE_TAG: ${{ github.sha }}
          CHANGE_CAUSE: ${{ github.event.release.tag_name }}

  build-and-deploy-app:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: 'upload'
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          app_build_command: 'npm run build:app:dev'
          output_location: 'packages/app/dist/zskarte/browser' # Built app content directory - optional
          config_file_location: 'packages/app/' # Config file path - optional
          ###### End of Repository/Build Configurations ######
